// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `err_fn`, `exercise_note_to_frequency`, `generate_piano_frequency`, `new`, `root_note_to_frequency`, `write_data_timed`, `write_data`
// These types are ignored because they are not used by any `pub` functions: `Player`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<void> playSound() => RustLib.instance.api.crateApiSimplePlaySound();
