// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'notes.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> startPlaying({required Set<Note> notes}) =>
    RustLib.instance.api.crateApiSimpleStartPlaying(notes: notes);

Future<void> stopPlaying() => RustLib.instance.api.crateApiSimpleStopPlaying();

Future<void> initWavFilesFromBytes({required List<Uint8List> wavData}) =>
    RustLib.instance.api.crateApiSimpleInitWavFilesFromBytes(wavData: wavData);
