pub const FADE_IN_DURATION: u64 = 2;
pub const FADE_OUT_DURATION: u64 = 2;

pub const RELATIVE_FULL_VOLUME_DURATION: u64 = 3;

pub const RELATIVE_CHALLENGE_FADE_IN_START_TIME: u64 = 2;
pub const RELATIVE_CHALLENGE_FULL_VOLUME_START_TIME: u64 =
    RELATIVE_CHALLENGE_FADE_IN_START_TIME + FADE_IN_DURATION;
pub const RELATIVE_CHALLENGE_FADE_OUT_START_TIME: u64 =
    RELATIVE_CHALLENGE_FULL_VOLUME_START_TIME + RELATIVE_FULL_VOLUME_DURATION;
pub const RELATIVE_CHALLENGE_END_TIME: u64 =
    RELATIVE_CHALLENGE_FADE_OUT_START_TIME + FADE_OUT_DURATION;

pub const RELATIVE_ANSWER_FADE_IN_START_TIME: u64 = PLAY_VOICE_ANSWER_START_TIME + 2;
pub const RELATIVE_ANSWER_FULL_VOLUME_START_TIME: u64 =
    RELATIVE_ANSWER_FADE_IN_START_TIME + FADE_IN_DURATION;
pub const RELATIVE_ANSWER_FADE_OUT_START_TIME: u64 =
    RELATIVE_ANSWER_FULL_VOLUME_START_TIME + RELATIVE_FULL_VOLUME_DURATION;
pub const RELATIVE_ANSWER_END_TIME: u64 = RELATIVE_ANSWER_FADE_OUT_START_TIME + FADE_OUT_DURATION;

pub const ROOT_FADE_IN_START_TIME: u64 = 0;
pub const ROOT_FULL_VOLUME_START_TIME: u64 = ROOT_FADE_IN_START_TIME + FADE_IN_DURATION;
pub const ROOT_FADE_OUT_START_TIME: u64 = RELATIVE_ANSWER_END_TIME;
pub const ROOT_END_TIME: u64 = ROOT_FADE_OUT_START_TIME + FADE_OUT_DURATION;

pub const ROOT_FULL_VOLUME_DURATION: u64 = ROOT_FADE_OUT_START_TIME - ROOT_FULL_VOLUME_START_TIME;

pub const PLAY_VOICE_ANSWER_START_TIME: u64 = RELATIVE_CHALLENGE_END_TIME + 1;
